export const projects = [
  {
    teamId: 1,
    teamName: 'Project 1',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is project 1',
    teamStar: 4,
  },
  {
    teamId: 2,
    teamName: 'Project 2',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is project 2',
    teamStar: 3,
  },
  {
    teamId: 3,
    teamName: 'Project 3',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is project 3',
    teamStar: 5,
  },
  {
    teamId: 4,
    teamName: 'Project 4',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is project 4',
    teamStar: 2,
  },
  {
    teamId: 5,
    teamName: 'Project 5',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is project 5',
    teamStar: 5,
  },
  {
    teamId: 6,
    teamName: 'Project 6',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is project 6',
    teamStar: 1,
  },
  {
    teamId: 7,
    teamName: 'Project 7',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is project 7',
    teamStar: 3,
  },
  {
    teamId: 8,
    teamName: 'Project 8',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is project 8',
    teamStar: 5,
  },
  {
    teamId: 9,
    teamName: 'Project 9',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is project 9',
    teamStar: 2,
  },
  {
    teamId: 10,
    teamName: 'Project 10',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is project 10',
    teamStar: 4,
  },
];

export const studies = [
  {
    teamId: 1,
    teamName: 'Study 1',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is study 1',
    teamStar: 4,
  },
  {
    teamId: 2,
    teamName: 'Study 2',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is study 2',
    teamStar: 3,
  },
  {
    teamId: 3,
    teamName: 'Study 3',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is study 3',
    teamStar: 5,
  },
  {
    teamId: 4,
    teamName: 'Study 4',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is study 4',
    teamStar: 2,
  },
  {
    teamId: 5,
    teamName: 'Study 5',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is study 5',
    teamStar: 5,
  },
  {
    teamId: 6,
    teamName: 'Study 6',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is study 6',
    teamStar: 1,
  },
  {
    teamId: 7,
    teamName: 'Study 7',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is study 7',
    teamStar: 3,
  },
  {
    teamId: 8,
    teamName: 'Study 8',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is study 8',
    teamStar: 5,
  },
  {
    teamId: 9,
    teamName: 'Study 9',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is study 9',
    teamStar: 2,
  },
  {
    teamId: 10,
    teamName: 'Study 10',
    teamImage: 'https://picsum.photos/200/300',
    teamDescription: 'This is study 10',
    teamStar: 4,
  },
];