export const projects = [
  {
    id: 1,
    title: 'Project 1',
    description: 'This is project 1',
    likes: 4,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 2,
    title: 'Project 2',
    description: 'This is project 2',
    likes: 3,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 3,
    title: 'Project 3',
    description: 'This is project 3',
    likes: 5,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 4,
    title: 'Project 4',
    description: 'This is project 4',
    likes: 2,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 5,
    title: 'Project 5',
    description: 'This is project 5',
    likes: 5,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 6,
    title: 'Project 6',
    description: 'This is project 6',
    likes: 1,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 7,
    title: 'Project 7',
    description: 'This is project 7',
    likes: 3,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 8,
    title: 'Project 8',
    description: 'This is project 8',
    likes: 5,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 9,
    title: 'Project 9',
    description: 'This is project 9',
    likes: 2,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 10,
    title: 'Project 10',
    description: 'This is project 10',
    likes: 4,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
];

export const studies = [
  {
    id: 1,
    title: 'Study 1',
    description: 'This is study 1',
    likes: 4,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 2,
    title: 'Study 2',
    description: 'This is study 2',
    likes: 3,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 3,
    title: 'Study 3',
    description: 'This is study 3',
    likes: 5,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 4,
    title: 'Study 4',
    description: 'This is study 4',
    likes: 2,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 5,
    title: 'Study 5',
    description: 'This is study 5',
    likes: 5,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 6,
    title: 'Study 6',
    description: 'This is study 6',
    likes: 1,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 7,
    title: 'Study 7',
    description: 'This is study 7',
    likes: 3,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 8,
    title: 'Study 8',
    description: 'This is study 8',
    likes: 5,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 9,
    title: 'Study 9',
    description: 'This is study 9',
    likes: 2,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 10,
    title: 'Study 10',
    description: 'This is study 10',
    likes: 4,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
];