import {IProject} from "../constant/interfaces.ts";

export const projects: IProject = {
  teamSearchResponseList:[
    {
      id: 1,
      title: 'Project 1',
      description: 'This is project 1',
      like: 4,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 2,
      title: 'Project 2',
      description: 'This is project 2',
      like: 3,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 3,
      title: 'Project 3',
      description: 'This is project 3',
      like: 5,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 4,
      title: 'Project 4',
      description: 'This is project 4',
      like: 2,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 5,
      title: 'Project 5',
      description: 'This is project 5',
      like: 5,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 6,
      title: 'Project 6',
      description: 'This is project 6',
      like: 1,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 7,
      title: 'Project 7',
      description: 'This is project 7',
      like: 3,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 8,
      title: 'Project 8',
      description: 'This is project 8',
      like: 5,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 9,
      title: 'Project 9',
      description: 'This is project 9',
      like: 2,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 10,
      title: 'Project 10',
      description: 'This is project 10',
      like: 4,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
  ],
  size: 0,
  hasNextSlice: true,
};

export const studies: IProject = {
  teamSearchResponseList: [
    {
      id: 1,
      title: 'Study 1',
      description: 'This is study 1',
      like: 4,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 2,
      title: 'Study 2',
      description: 'This is study 2',
      like: 3,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 3,
      title: 'Study 3',
      description: 'This is study 3',
      like: 5,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 4,
      title: 'Study 4',
      description: 'This is study 4',
      like: 2,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 5,
      title: 'Study 5',
      description: 'This is study 5',
      like: 5,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 6,
      title: 'Study 6',
      description: 'This is study 6',
      like: 1,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 7,
      title: 'Study 7',
      description: 'This is study 7',
      like: 3,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 8,
      title: 'Study 8',
      description: 'This is study 8',
      like: 5,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 9,
      title: 'Study 9',
      description: 'This is study 9',
      like: 2,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
    {
      id: 10,
      title: 'Study 10',
      description: 'This is study 10',
      like: 4,
      thumbnailUrl: 'https://picsum.photos/200/300',
    },
  ],
  size: 0,
  hasNextSlice: true,
}

export const feeds = [
  {
    title: 'Feed 1',
    description: 'This is feed 1',
    image: 'https://picsum.photos/200/300',
    date: '2021-01-01',
  },
  {
    title: 'Feed 2',
    description: 'This is feed 2',
    image: 'https://picsum.photos/200/300',
    date: '2021-01-02',
  },
  {
    title: 'Feed 3',
    description: 'This is feed 3',
    image: 'https://picsum.photos/200/300',
    date: '2021-01-03',
  },
  {
    title: 'Feed 4',
    description: 'This is feed 4',
    image: 'https://picsum.photos/200/300',
    date: '2021-01-04',
  },
  {
    title: 'Feed 5',
    description: 'This is feed 5',
    image: 'https://picsum.photos/200/300',
    date: '2021-01-05',
  },
  {
    title: 'Feed 6',
    description: 'This is feed 6',
    image: 'https://picsum.photos/200/300',
    date: '2021-01-06',
  },
  {
    title: 'Feed 7',
    description: 'This is feed 7',
    image: 'https://picsum.photos/200/300',
    date: '2021-01-07',
  },
  {
    title: 'Feed 8',
    description: 'This is feed 8',
    image: 'https://picsum.photos/200/300',
    date: '2021-01-08',
  },
  {
    title: 'Feed 9',
    description: 'This is feed 9',
    image: 'https://picsum.photos/200/300',
    date: '2021-01-09',
  },
  {
    title: 'Feed 10',
    description: 'This is feed 10',
    image: 'https://picsum.photos/200/300',
    date: '2021-01-10',
  },
];

export const mentors = [
  {
    id: 1,
    name: 'Mentor 1',
    description: 'This is mentor 1',
    heart: 4,
    star: 3,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 2,
    name: 'Mentor 2',
    description: 'This is mentor 2',
    heart: 3,
    star: 2,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 3,
    name: 'Mentor 3',
    description: 'This is mentor 3',
    heart: 5,
    star: 4,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 4,
    name: 'Mentor 4',
    description: 'This is mentor 4',
    heart: 2,
    star: 1,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 5,
    name: 'Mentor 5',
    description: 'This is mentor 5',
    heart: 5,
    star: 4,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 6,
    name: 'Mentor 6',
    description: 'This is mentor 6',
    heart: 1,
    star: 2,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 7,
    name: 'Mentor 7',
    description: 'This is mentor 7',
    heart: 3,
    star: 4,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 8,
    name: 'Mentor 8',
    description: 'This is mentor 8',
    heart: 5,
    star: 5,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 9,
    name: 'Mentor 9',
    description: 'This is mentor 9',
    heart: 2,
    star: 3,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
  {
    id: 10,
    name: 'Mentor 10',
    description: 'This is mentor 10',
    heart: 4,
    star: 5,
    thumbnailUrl: 'https://picsum.photos/200/300',
  },
];